### ISSUE TITLE
Browser throws error when requesting data

### ISSUE THREAD

**Issue by eden-u** [yuko1101/starrail.js#127]
I installed node-polyfills and defined __dirname and __filename

![config](https://github.com/yuko1101/starrail.js/assets/140721745/0e5e94bf-f381-4bdd-a278-f0bb26e0bd4e)

But because of using the getAllCharacters function, a path error occurred

![app](https://github.com/yuko1101/starrail.js/assets/140721745/dc334d45-1fc5-4eb5-aa60-1c2e6883f4a7)
![error](https://github.com/yuko1101/starrail.js/assets/140721745/15a72ff5-3132-4990-b2eb-ec9cd3b8e42e)

Is there any good way to make the path section error-free?
I use Google Translate, please forgive my English, thank you

**Comment by yuko1101** [comment]
Thanks for reporting this, but starrail.js should not be used on the frontend.
Try using it on the backend or SSR instead.

**Comment by eden-u** [comment]
OK, thanks for the reply
