### ISSUE TITLE
[Request] Allow to export json files

### ISSUE THREAD

**Issue by Zyr0nX** [yuko1101/starrail.js#28]
When using this library, I often run into out of memory problem. It would be better if the data can be exported into a json file for convenient uses, instead of reading the gigantic raw files everytime I need the data

**Comment by yuko1101** [comment]
Hi. Thank you for your issue!

I'm sorry but I won't provide any features about it.
Just create your own function to convert starrail.js objects to json.

e.g.
```js
const keyBlacklists = ["client"];
function jsonize(obj) {
    if (typeof obj !== "object" || obj === null || obj === undefined) return obj;
    const entries = Object.entries(obj).filter(([key]) => !keyBlacklists.includes(key) && !key.startsWith("_")).map(([key, value]) => [key, jsonize(value)]);
    if (obj instanceof TextAssets) {
        entries.push(["text", obj instanceof DynamicTextAssets ? obj.getNullableReplacedText() : obj.getNullable()]);
    }
    return Object.fromEntries(entries);
}
```

Then pass the object that you'd like to convert to json, and save it into a file.
```js
const user = await client.fetchUser(800069903);

const json = jsonize(user);
fs.writeFileSync("./user.json", JSON.stringify(json));
```

**Comment by yuko1101** [comment]
Also, what is the memory usage of this library? It does not exceed 100MB in my environment.

If it is over 100MB, I might be able to improve it.

**Comment by Zyr0nX** [comment]
Hi, sorry for the late reply. Apperantly my issue is not relate to the memory usage, rather than next.js can't serialize the object returned by starrail.js. I will close this issue for now.
